### PR TITLE
Add Arabic localizations

### PR DESCRIPTION
**Pull request by Milad-Akarie**

### CODE REVIEW

**Comment by kekland** [comment]
Hi! @Milad-Akarie, thanks for your contribution! This will be released as a minor update in the next day.

Just to confirm - does the RTL layout look good on the built-in Material and Cupertino croppers? I'm not too familiar with RTL layouts to spot if anything looks odd

**Comment by kekland** [comment]
I'll merge this, assuming that everything looks good :P

Let me know here if anything needs to be tweaked or changed in terms of the layout.

**Comment by kekland** [comment]
Deployed in version 1.1.1

**Comment by Milad-Akarie** [comment]
Hey @kekland sorry for the late response, I'm swamped, Yes, RTL layout looks fine.
Thanks for this great package btw. 

I have a little suggestion regarding the fact that the locale must be supported for the package to work, I'm working on an App that only supports AR locale and the plugin would just throw an error, I was in a stage when I wanted to test the plugin before I invest time in creating a PR that adds my locale, so I'd suggest that the plugin use a default locale, "EN"  for example when the requested locale is not supported.

**Comment by kekland** [comment]
Good catch, I didn't think that would throw. First time trying to add localization to a package :P

Will fix this tomorrow

**Pull request merged**
