### PR TITLE
Add german translations

### PR DESCRIPTION
**Pull request by jkoenig134**

### CODE REVIEW

**Comment by jkoenig134** [comment]
@kekland I was just adding this to my app and thought why not PR this :)

**Comment by kekland** [comment]
Thanks a lot! Will merge and release sometime soon

**Comment by jkoenig134** [comment]
@kekland just a reminder to release the translation

**Comment by kekland** [comment]
@jkoenig134 sorry, completely went out of my head, working on a bunch of stuff right now :D will do in a moment

**Comment by kekland** [comment]
@jkoenig134 deployed in 1.3.1

**Comment by jkoenig134** [comment]
Thanks!

**Pull request merged**
